apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpro-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/M0ngi/K8S-ArgoCD-Springboot-Manifest.git
    targetRevision: HEAD
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
