apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-dashboard-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx
  rules:
    - host: mp.k8s.argocd.securinets.tn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
